import XCTest
@testable import CodixxCore

final class LocalizationTests: XCTestCase {
    func testEnglishStringsExplainUnsavedCurrentAccount() {
        let strings = CodixxStrings(language: .english)

        XCTAssertEqual(strings.noActiveAccountTitle, "No saved current account")
        XCTAssertEqual(strings.noActiveAccountDetail, "Save the current Codex auth in Accounts to show account quota here.")
        XCTAssertEqual(strings.languageLabel, "Language")
        XCTAssertEqual(strings.confidenceLabel(.unknown), "Quota unknown")
        XCTAssertEqual(strings.fiveHourQuotaWithConfidence("Fresh quota"), "5-hour quota / Fresh quota")
        XCTAssertEqual(strings.weeklyPercent(15), "Weekly quota 15%")
        XCTAssertEqual(strings.primaryQuota(primary: "94%", confidence: "Fresh quota"), "5-hour 94% / Fresh quota")
        XCTAssertEqual(strings.savedCurrentAccount(alias: "Main"), "Saved Main.")
        XCTAssertEqual(strings.couldNotSaveCurrentAccount("Missing token"), "Could not save current account: Missing token")
        XCTAssertEqual(strings.switchSuccessTitle(target: "Main"), "Switched to Main")
        XCTAssertEqual(strings.addAccount, "Add Account")
        XCTAssertEqual(strings.logs, "Logs")
        XCTAssertEqual(strings.switchTriggerLabel(.autoPrimaryThreshold), "Automatic")
        XCTAssertEqual(strings.switchTriggerLabel(.manual), "Manual")
        XCTAssertEqual(strings.switchTriggerLabel(.recovery), "Recovery")
        XCTAssertEqual(strings.switchResultLabel(.failedValidation), "Validation failed")
        XCTAssertEqual(strings.errorSummaryLabel, "Error")
        XCTAssertEqual(strings.backupPathLabel, "Backup")
        XCTAssertEqual(strings.switchAccount, "Switch to account")
        XCTAssertEqual(strings.renameAccount, "Rename account")
        XCTAssertEqual(strings.cancelEdit, "Cancel edit")
        XCTAssertEqual(strings.deleteAccount, "Delete account")
        XCTAssertEqual(strings.neverExpires, "Expiration unavailable locally")
        XCTAssertEqual(strings.autoSwitchNeedsTwoAccounts, "Save a second enabled account to use auto switch.")
        XCTAssertEqual(strings.quotaRefresh, "Quota refresh")
        XCTAssertEqual(strings.usageRefresh, "Usage refresh")
        XCTAssertEqual(strings.secondsInterval(60), "60s")
        XCTAssertEqual(strings.minutesInterval(5), "5m")
        XCTAssertEqual(strings.activeThread, "Active thread")
        XCTAssertEqual(strings.noActiveThread, "No active thread")
        XCTAssertEqual(strings.fiveHourQuota, "5-hour quota")
        XCTAssertEqual(strings.weeklyQuota, "Weekly quota")
        XCTAssertEqual(strings.todayTokens, "Today")
        XCTAssertEqual(strings.yesterdayTokens, "Yesterday")
        XCTAssertEqual(strings.membership, "Membership")
        XCTAssertEqual(strings.postSwitchAction, "After switch")
        XCTAssertEqual(strings.codexRestartRequired, "Restart Codex required")
        XCTAssertEqual(strings.postSwitchActionLabel(.restartCodexApp), "Restart Codex")
        XCTAssertEqual(strings.restartCodexNow, "Restart Codex now")
        XCTAssertFalse(strings.resets(Date(timeIntervalSince1970: 1_777_000_000)).contains("5-hour quota"))
        XCTAssertFalse(strings.weeklyResets(Date(timeIntervalSince1970: 1_777_000_000)).contains("Weekly quota"))
        XCTAssertTrue(strings.weeklyResets(Date(timeIntervalSince1970: 1_777_000_000)).contains("2026"))
    }

    func testChineseStringsExplainUnsavedCurrentAccount() {
        let strings = CodixxStrings(language: .chinese)

        XCTAssertEqual(strings.noActiveAccountTitle, "尚未保存当前账号")
        XCTAssertEqual(strings.noActiveAccountDetail, "请先在“账号”里保存当前 Codex 登录，之后这里会显示账号额度。")
        XCTAssertEqual(strings.languageLabel, "语言")
        XCTAssertEqual(strings.confidenceLabel(.unknown), "额度未知")
        XCTAssertEqual(strings.fiveHourQuotaWithConfidence("额度信息新鲜"), "5 小时额度 / 额度信息新鲜")
        XCTAssertEqual(strings.weeklyPercent(15), "每周额度 15%")
        XCTAssertEqual(strings.primaryQuota(primary: "94%", confidence: "额度信息新鲜"), "5 小时 94% / 额度信息新鲜")
        XCTAssertEqual(strings.savedCurrentAccount(alias: "Main"), "已保存 Main。")
        XCTAssertEqual(strings.couldNotSaveCurrentAccount("缺少令牌"), "无法保存当前账号：缺少令牌")
        XCTAssertEqual(strings.switchSuccessTitle(target: "Main"), "已切换到 Main")
        XCTAssertEqual(strings.addAccount, "添加账号")
        XCTAssertEqual(strings.logs, "日志")
        XCTAssertEqual(strings.switchTriggerLabel(.autoPrimaryThreshold), "自动切换")
        XCTAssertEqual(strings.switchTriggerLabel(.manual), "手动切换")
        XCTAssertEqual(strings.switchTriggerLabel(.recovery), "恢复")
        XCTAssertEqual(strings.switchResultLabel(.failedValidation), "校验失败")
        XCTAssertEqual(strings.errorSummaryLabel, "错误")
        XCTAssertEqual(strings.backupPathLabel, "备份")
        XCTAssertEqual(strings.switchAccount, "切换到此账号")
        XCTAssertEqual(strings.renameAccount, "重命名账号")
        XCTAssertEqual(strings.cancelEdit, "取消编辑")
        XCTAssertEqual(strings.deleteAccount, "删除账号")
        XCTAssertEqual(strings.neverExpires, "本地未提供到期时间")
        XCTAssertEqual(strings.autoSwitchNeedsTwoAccounts, "请先保存第二个已启用账号，再使用自动切换。")
        XCTAssertEqual(strings.quotaRefresh, "额度刷新")
        XCTAssertEqual(strings.usageRefresh, "用量刷新")
        XCTAssertEqual(strings.secondsInterval(60), "60 秒")
        XCTAssertEqual(strings.minutesInterval(5), "5 分钟")
        XCTAssertEqual(strings.activeThread, "活跃会话")
        XCTAssertEqual(strings.noActiveThread, "暂无活跃会话")
        XCTAssertEqual(strings.fiveHourQuota, "5 小时额度")
        XCTAssertEqual(strings.weeklyQuota, "周额度")
        XCTAssertEqual(strings.todayTokens, "今日 token 用量")
        XCTAssertEqual(strings.yesterdayTokens, "昨日 token 用量")
        XCTAssertEqual(strings.membership, "会员")
        XCTAssertEqual(strings.postSwitchAction, "切换后动作")
        XCTAssertEqual(strings.codexRestartRequired, "需要重启 Codex")
        XCTAssertEqual(strings.postSwitchActionLabel(.restartCodexApp), "重启 Codex")
        XCTAssertEqual(strings.restartCodexNow, "立即重启 Codex")
        XCTAssertFalse(strings.resets(Date(timeIntervalSince1970: 1_777_000_000)).contains("5 小时额度"))
        XCTAssertFalse(strings.weeklyResets(Date(timeIntervalSince1970: 1_777_000_000)).contains("周额度"))
        XCTAssertTrue(strings.weeklyResets(Date(timeIntervalSince1970: 1_777_000_000)).contains("2026"))
    }
}
